INSERT INTO movies (id, title, description, status, created_at, updated_at, qualities_json,
                    vertical_poster, horizontal_poster, release_date, trailer_url, age, year, country)
VALUES (uuid_generate_v4(), 'Interstellar',
        'A team of explorers travel through a wormhole to ensure humanity’s survival.',
        'READY', NOW(), NOW(),
        '{"1080p":"movies/interstellar/1080p/index.m3u8","4K":"movies/interstellar/4k/index.m3u8","master":"movies/interstellar/master.m3u8"}', 'poster_v_interstellar.jpg', 'poster_h_interstellar.jpg',
        '2014-11-07', 'https://youtu.be/zSWdZVtXT7E', 13, 2014, 'USA'),

       (uuid_generate_v4(), 'Inception',
        'A skilled thief is offered a chance to erase his past crimes by planting an idea into someone’s subconscious.',
        'READY', NOW(), NOW(),
        '{"720p":"movies/inception/720p/index.m3u8","1080p":"movies/inception/1080p/index.m3u8","master":"movies/inception/master.m3u8"}', 'poster_v_inception.jpg', 'poster_h_inception.jpg',
        '2010-07-16', 'https://youtu.be/YoHD9XEInc0', 13, 2010, 'USA'),

       (uuid_generate_v4(), 'Parasite',
        'A poor family schemes to become employed by a wealthy family by infiltrating their household.',
        'READY', NOW(), NOW(),
        '{"1080p":"movies/parasite/1080p/index.m3u8","4K":"movies/parasite/4k/index.m3u8","master":"movies/parasite/master.m3u8"}', 'poster_v_parasite.jpg', 'poster_h_parasite.jpg',
        '2019-05-30', 'https://youtu.be/SEUXfv87Wpk', 16, 2019, 'Korea'),

       (uuid_generate_v4(), 'The Dark Knight',
        'Batman faces his nemesis, the Joker, who seeks to create chaos in Gotham.',
        'READY', NOW(), NOW(),
        '{"1080p":"movies/the-dark-knight/1080p/index.m3u8","4K":"movies/the-dark-knight/4k/index.m3u8","master":"movies/the-dark-knight/master.m3u8"}', 'poster_v_dark_knight.jpg', 'poster_h_dark_knight.jpg',
        '2008-07-18', 'https://youtu.be/EXeTwQWrcwY', 13, 2008, 'USA'),

       (uuid_generate_v4(), 'Dune: Part Two',
        'Paul Atreides unites with the Fremen to exact revenge against the conspirators who destroyed his family.',
        'PROCESSING', NOW(), NOW(),
        '{"1080p":"movies/dune-part-two/1080p/index.m3u8","4K":"movies/dune-part-two/4k/index.m3u8","master":"movies/dune-part-two/master.m3u8"}', 'poster_v_dune2.jpg', 'poster_h_dune2.jpg',
        '2024-03-01', 'https://youtu.be/U2Qp5pL3ovA', 13, 2024, 'USA'),

       (uuid_generate_v4(), 'Oppenheimer',
        'The story of J. Robert Oppenheimer and his role in the development of the atomic bomb.',
        'READY', NOW(), NOW(),
        '{"1080p":"movies/oppenheimer/1080p/index.m3u8","4K":"movies/oppenheimer/4k/index.m3u8","master":"movies/oppenheimer/master.m3u8"}', 'poster_v_oppenheimer.jpg', 'poster_h_oppenheimer.jpg',
        '2023-07-21', 'https://youtu.be/uYPbbksJxIg', 16, 2023, 'USA'),

       (uuid_generate_v4(), 'Your Name',
        'Two teenagers share a profound, magical connection upon discovering they are swapping bodies.',
        'READY', NOW(), NOW(),
        '{"720p":"movies/your-name/720p/index.m3u8","1080p":"movies/your-name/1080p/index.m3u8","master":"movies/your-name/master.m3u8"}', 'poster_v_yourname.jpg', 'poster_h_yourname.jpg',
        '2016-08-26', 'https://youtu.be/xU47nhruN-Q', 10, 2016, 'Japan'),

       (uuid_generate_v4(), 'Spirited Away',
        'A young girl becomes trapped in a mysterious spirit world after her parents are transformed into pigs.',
        'READY', NOW(), NOW(),
        '{"1080p":"movies/spirited-away/1080p/index.m3u8","master":"movies/spirited-away/master.m3u8"}', 'poster_v_spirited_away.jpg', 'poster_h_spirited_away.jpg',
        '2001-07-20', 'https://youtu.be/ByXuk9QqQkk', 7, 2001, 'Japan'),

       (uuid_generate_v4(), 'The Godfather',
        'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.',
        'READY', NOW(), NOW(),
        '{"1080p":"movies/the-godfather/1080p/index.m3u8","master":"movies/the-godfather/master.m3u8"}', 'poster_v_godfather.jpg', 'poster_h_godfather.jpg',
        '1972-03-24', 'https://youtu.be/sY1S34973zA', 18, 1972, 'USA'),

       (uuid_generate_v4(), 'Train to Busan',
        'A zombie outbreak traps passengers on a speeding train to Busan.',
        'READY', NOW(), NOW(),
        '{"720p":"movies/train-to-busan/720p/index.m3u8","1080p":"movies/train-to-busan/1080p/index.m3u8","master":"movies/train-to-busan/master.m3u8"}', 'poster_v_train_busan.jpg', 'poster_h_train_busan.jpg',
        '2016-07-20', 'https://youtu.be/pyWuHv2-Abk', 16, 2016, 'Korea');
